apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bravo

resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - rabbitmq.yaml
  - wiremock.yaml
  - api.yaml
  - ingress.yaml
